{% set name = "geoalchemy2" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoalchemy2-{{ version }}.tar.gz
  sha256: 33df0cd901abf8518ec0985f9201d42cce65887127cf59f40be38cf758a9a6dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.7
    - sqlalchemy >=1.4
    - packaging

test:
  imports:
    - geoalchemy2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geoalchemy-2.readthedocs.io/en/latest/
  summary: Using SQLAlchemy with Spatial Databases
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2

extra:
  recipe-maintainers:
    - swainn
    - pmlandwehr
    - ocefpaf
    - matttriano
