{% set name = "GeoAlchemy2" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GeoAlchemy2-{{ version }}.tar.gz
  sha256: 8ca023dcb9a36c6d312f3b4aee631d66385264e2fc9feb0ab0f446eb5609407d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.7
    - sqlalchemy >=1.4
    - packaging

test:
  imports:
    - geoalchemy2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geoalchemy-2.readthedocs.io/en/latest/
  summary: Using SQLAlchemy with Spatial Databases
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2

extra:
  recipe-maintainers:
    - swainn
    - pmlandwehr
    - ocefpaf
    - matttriano
