{% set name = "GeoAlchemy2" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "ec2a6e9919b522631803ac5922e88b701081da7e5d56a68f10ff263f6592d552" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  preserve_egg_dir: true
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - sqlalchemy >=0.8

test:
  imports:
    - geoalchemy2

about:
  home: http://geoalchemy.org/
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  summary: Using SQLAlchemy with Spatial Databases
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
