{% set python_min = "3.10" %}
{% set name = "geoalchemy2" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geoalchemy2-{{ version }}.tar.gz
  sha256: 4bdc7daf659e36f6456e2f2c3bcce222b879584921a4f50a803ab05fa2bb3124

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.4
    - packaging

test:
  imports:
    - geoalchemy2
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://geoalchemy-2.readthedocs.io/en/latest/
  summary: Using SQLAlchemy with Spatial Databases
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2

extra:
  recipe-maintainers:
    - swainn
    - pmlandwehr
    - ocefpaf
    - matttriano
